data:
  APPINSIGHTS_INSTRUMENTATIONKEY: NWMyYWQzNGUtNjVhZi00OTk5LTkxZGQtMjE3Zjk4YzhiZTQ5
  APPLICATIONINSIGHTS_CONNECTION_STRING: SW5zdHJ1bWVudGF0aW9uS2V5PTVjMmFkMzRlLTY1YWYtNDk5OS05MWRkLTIxN2Y5OGM4YmU0OTtJbmdlc3Rpb25FbmRwb2ludD1odHRwczovL2NlbnRyYWxpbmRpYS0wLmluLmFwcGxpY2F0aW9uaW5zaWdodHMuYXp1cmUuY29tLztMaXZlRW5kcG9pbnQ9aHR0cHM6Ly9jZW50cmFsaW5kaWEubGl2ZWRpYWdub3N0aWNzLm1vbml0b3IuYXp1cmUuY29tLw==
  AzureWebJobsStorage: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPW15c3RvcmFnZWFjY291bnRjaTtBY2NvdW50S2V5PVRHZGxzUGQxSk1COUpWYzVQSlBCS3B3WkdiZkYyU2ZXNktmK2pEelZCY2NvRzlrWkxkOWQ0N3JKbEdpRzV3cUpxTno4T0Qra016SjYrQVN0ZEp0V1FRPT07RW5kcG9pbnRTdWZmaXg9Y29yZS53aW5kb3dzLm5ldA==
  FUNCTIONS_EXTENSION_VERSION: fjQ=
  FUNCTIONS_WORKER_RUNTIME: cHl0aG9u
  mydatabaseci: bW9uZ29kYjovL215Y29zbW9zZGJmb3Jtb25nb2RiY2k6V0p3SHFvdUNzeXUxZDNMRUJlQXNqVEJCdkhtcEs4M21NeDNhekdwMGdVSE8yZk5INVhXZ1BBdVNwTnlDOGU3cnNQZzYzMk54Sm9SSEFDRGJqVzJpR1E9PUBteWNvc21vc2RiZm9ybW9uZ29kYmNpLm1vbmdvLmNvc21vcy5henVyZS5jb206MTAyNTUvP3NzbD10cnVlJnJlcGxpY2FTZXQ9Z2xvYmFsZGImcmV0cnl3cml0ZXM9ZmFsc2UmbWF4SWRsZVRpbWVNUz0xMjAwMDAmYXBwTmFtZT1AbXljb3Ntb3NkYmZvcm1vbmdvZGJjaUA=
  WEBSITE_CONTENTAZUREFILECONNECTIONSTRING: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPW15c3RvcmFnZWFjY291bnRjaTtBY2NvdW50S2V5PVRHZGxzUGQxSk1COUpWYzVQSlBCS3B3WkdiZkYyU2ZXNktmK2pEelZCY2NvRzlrWkxkOWQ0N3JKbEdpRzV3cUpxTno4T0Qra016SjYrQVN0ZEp0V1FRPT07RW5kcG9pbnRTdWZmaXg9Y29yZS53aW5kb3dzLm5ldA==
  WEBSITE_CONTENTSHARE: bXlmdW5jdGlvbmFwcGNpODRiMw==
apiVersion: v1
kind: Secret
metadata:
  name: myfunctionappci
---
data:
  host.master: azhHMUgwZUZQU0N6RUJNXy1BdHd3S2ItcEd5RmpINWotUVNpX21RYlMtaHFBekZ1Mi1FSTF3PT0=
  host.function.default: U25Mcm9DZnY5R1hlQmJiMUxCbXVON1BFVEZEQm1BTzRrWE9wNWRJT2QxTmJBekZ1eWVUYktRPT0=
  host.systemKey.default: NEI1YmUySG1ZWGlSc0pqYkY3dUFuNkpyVldzamJKNXp5VWswTWd5dUZyS0ZBekZ1aVVIU2lBPT0=
  functions.createadvertisement.default: ZjJRN0laV1Zjajd0UHMycFNkRnZGZUhTV3QwTlU3dVViWlFvaEx5TmRSWEdBekZ1QU1wTm5nPT0=
  functions.deleteadvertisement.default: VlhHaG5TNFljTjc5cFR6Sm9kMjU5SE01Q1hzdUI3S1BjTGlmejllNlR5Z0pBekZ1LXpnNlNnPT0=
  functions.getadvertisement.default: S216WExCTEVQdlAxYVdfZ2dibjhxVENtMnB1Qi10OElHV21pUE9pLU5GR2tBekZ1UGQ4cHNBPT0=
  functions.getadvertisements.default: WnNob0lwSEViZjEwdWpFZVBuUUk3YVpYNWVjNUxTMUp4eDFnTHRnRDNreWJBekZ1TDlWUnRBPT0=
  functions.getpost.default: WGlGR1BnZllTZDh0dF9vUklKejJBT0owZF9xQ01SRlh5T1NwQklRZ3p2el9BekZ1NTNzb0hnPT0=
  functions.getposts.default: amQyMjVaVXFRRnp1QjdpUjd3dHpGS2ZSY01GLW8zQUhLVXhyUWhsTDBfWUVBekZ1SXVobzN3PT0=
  functions.updateadvertisement.default: Y3hYUE9WSGJCM1A4MWI4QTRGcXNSMzZNUnBZSW56Z1p6MlB4ak92UTMzSkdBekZ1RFNzUGdnPT0=
apiVersion: v1
kind: Secret
metadata:
  name: func-keys-kube-secret-myfunctionappci
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: myfunctionappci-function-keys-identity-svc-act
---
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - configMaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: functions-keys-manager-role
---
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: functions-keys-manager-role
subjects:
  - kind: ServiceAccount
    name: myfunctionappci-function-keys-identity-svc-act
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: myfunctionappci-function-keys-identity-svc-act-functions-keys-manager-rolebinding
---
apiVersion: v1
kind: Service
metadata:
  name: myfunctionappci-http
spec:
  selector:
    app: myfunctionappci-http
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfunctionappci-http
  labels:
    app: myfunctionappci-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myfunctionappci-http
  template:
    metadata:
      labels:
        app: myfunctionappci-http
    spec:
      containers:
        - name: myfunctionappci-http
          image: myacr1995lab.azurecr.io/neighborlyapi:v1
          ports:
            - containerPort: 80
          env:
            - name: AzureFunctionsJobHost__functions__0
              value: createAdvertisement
            - name: AzureFunctionsJobHost__functions__1
              value: deleteAdvertisement
            - name: AzureFunctionsJobHost__functions__2
              value: getAdvertisement
            - name: AzureFunctionsJobHost__functions__3
              value: getAdvertisements
            - name: AzureFunctionsJobHost__functions__4
              value: getPost
            - name: AzureFunctionsJobHost__functions__5
              value: getPosts
            - name: AzureFunctionsJobHost__functions__6
              value: updateAdvertisement
            - name: AzureWebJobsSecretStorageType
              value: kubernetes
            - name: AzureWebJobsKubernetesSecretName
              value: secrets/func-keys-kube-secret-myfunctionappci
          envFrom:
            - secretRef:
                name: myfunctionappci
          readinessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 240
            httpGet:
              path: /
              port: 80
              scheme: HTTP
          startupProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 240
            httpGet:
              path: /
              port: 80
              scheme: HTTP
      serviceAccountName: myfunctionappci-function-keys-identity-svc-act
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfunctionappci
  labels:
    app: myfunctionappci
spec:
  selector:
    matchLabels:
      app: myfunctionappci
  template:
    metadata:
      labels:
        app: myfunctionappci
    spec:
      containers:
        - name: myfunctionappci
          image: myacr1995lab.azurecr.io/neighborlyapi:v1
          env:
            - name: AzureFunctionsJobHost__functions__0
              value: eventHubTrigger
          envFrom:
            - secretRef:
                name: myfunctionappci
          readinessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 240
            httpGet:
              path: /
              port: 80
              scheme: HTTP
          startupProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 240
            httpGet:
              path: /
              port: 80
              scheme: HTTP
      serviceAccountName: myfunctionappci-function-keys-identity-svc-act
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: myfunctionappci
  labels: {}
spec:
  scaleTargetRef:
    name: myfunctionappci
  triggers:
    - type: eventgridtrigger
      metadata:
        direction: in
        eventHubName: testhub
        connection: Endpoint=sb://udacityneighborly.servicebus.windows.net/;SharedAccessKeyName=allpolicy;SharedAccessKey=LOxUOkN13xN038T1VoSsmaTt4s7vq/+VCzduS5/nH9A=;EntityPath=testhub
---

